version: '3.8'

services:
  rag-frameworkless-api:
    build: .
    container_name: rag-frameworkless-api
    ports:
      - "5000:5000"  # Flask API port
      - "8502:8501"  # Streamlit UI port (optional)
    volumes:
      # Mount data directory for document uploads
      - ./data:/app/data
      # Mount database directory for persistent vector store
      - ./database:/app/database
      # Mount logs directory (optional)
      - ./logs:/app/logs
    environment:
      - PYTHONPATH=/app
      - PORT=5000
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      # Add your Groq API key here (or use .env file)
      # - GROQ_API_KEY=your_api_key_here
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    command: ["python", "app.py"]

  rag-frameworkless-ui:
    build: .
    container_name: rag-frameworkless-ui
    ports:
      - "8503:8501"  # Streamlit UI on different port
    volumes:
      # Mount data directory for document uploads
      - ./data:/app/data
      # Mount database directory for persistent vector store
      - ./database:/app/database
    environment:
      - PYTHONPATH=/app
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      # Add your Groq API key here (or use .env file)
      # - GROQ_API_KEY=your_api_key_here
    restart: unless-stopped
    depends_on:
      - rag-frameworkless-api
    command: ["streamlit", "run", "main.py", "--server.port=8501", "--server.address=0.0.0.0"]

volumes:
  data:
  database:
  logs: 